### ISSUE TITLE
添加钉钉机器人名称无法输入

### ISSUE THREAD

**Issue by YafengLiang** [qkqpttgf/Cloud189Checkin-Actions#5]
输入钉钉DDBOT的名称 系统报错，非法输入有遇到么？

> 

> [![](https://i.loli.net/2021/04/14/7DdKFNtXlGaqgVC.png)](url)

**Comment by YafengLiang** [comment]
帮助文档没说有什么限制哇
[![](https://i.loli.net/2021/04/14/8Bwgel1TEALYfKI.png)](url)

**Comment by qkqpttgf** [comment]
DDBOT  这5个字母怎么可能非法

**Comment by YafengLiang** [comment]
不知道什么情况，我换了个其他名称可以成功，设置了定时任务，每天并没有自动执行

**Comment by YafengLiang** [comment]
找到原因了，更改了定时任务的cron，python中和java中表达式不一样，java中0 2/13 * * * ？ 是每隔13分钟，这里的是0 2/13 * * *是每天2点和下午1点
